version: '3.8'

services:
  transaction-svc:
    image: transaction-service-stg
    command: npm run start
    ports:
      - "3008:3001"
    environment:
      - PORT=3001
      - MONGO_URI=mongodb://admin:admin@stg_mongo_transaction:27017
      - USER_SVC_NAME=user-service-user-svc-1:3001
    depends_on:
      - stg-mongo-transaction
    networks:
      - stg-net

  stg-mongo-transaction:
    image: mongo
    container_name: stg_mongo_transaction
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    networks:
        - stg-net
networks:
  stg-net:
    external: true
    name: stg-shared-net

