apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service-dev-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-dev-service
  template:
    metadata:
      labels:
        app: transaction-dev-service
    spec:
      containers:
        - name: transaction-dev-service
          image: transaction-service-dev
          imagePullPolicy: Never
          ports:
            - containerPort: 3002
          workingDir: /app   
          env:
            - name: PORT
              value: "3002"
            - name: MONGO_URI
              value: mongodb://admin:admin@mongo-service:27017
          command: ["npm", "run", "start:dev" ]
