apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service-prod-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-prod-service
  template:
    metadata:
      labels:
        app: transaction-prod-service
    spec:
      containers:
        - name: transaction-prod-service
          image: transaction-service-dev
          imagePullPolicy: Never
          ports:
            - containerPort: 3005
          workingDir: /app   
          env:
            - name: PORT
              value: "3005"
            - name: MONGO_URI
              value: mongodb://admin:admin@mongo-service:27017
          command: ["npm", "run", "start" ]
