apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: instapay-frontend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: mini-instapay.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: instapay-frontend
                port:
                  number: 80
