version: '3.8'

services:
  transaction-svc:
    image: transaction-service
    command: npm run start:dev
    ports:
      - "3002:3001"
    environment:
      - PORT=3001
      - MONGO_URI=mongodb://admin:admin@dev_mongo_transaction:27017
      - USER_SVC_NAME=user-service-user-svc-1:3001
    depends_on:
      - dev-mongo-transaction
    networks:
        - dev-net

  dev-mongo-transaction:
    image: mongo
    container_name: dev_mongo_transaction
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    networks:
        - dev-net
networks:
  dev-net:
    external: true
    name: dev-shared-net

