apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service-stg-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-stg-service
  template:
    metadata:
      labels:
        app: transaction-stg-service
    spec:
      containers:
        - name: transaction-stg-service
          image: transaction-service-dev
          imagePullPolicy: Never
          ports:
            - containerPort: 3008
          workingDir: /app   
          env:
            - name: PORT
              value: "3008"
            - name: MONGO_URI
              value: mongodb://admin:admin@mongo-service:27017
            - name: USER_SVC_NAME
              value: user-dev-service
          command: ["npm", "run", "start" ]
