version: '3.8'

services:
  user-svc:
    image: user-service-prod
    command: npm run start
    ports:
      - "3004:3001"
    environment:
      - PORT=3001
      - MONGO_URI=mongodb://admin:admin@prod_mongo_user:27017
    depends_on:
      - prod-mongo-user
    networks:
        - prod-net

  prod-mongo-user:
    image: mongo
    container_name: prod_mongo_user
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    networks:
        - prod-net
networks:
  prod-net:
    external: true
    name: prod-shared-net
