version: '3.8'

services:
  app:
    command: npm run start:dev
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - MONGO_URI=mongodb://admin:admin@dev_mongo:27017
    depends_on:
      - dev-mongo

  dev-mongo:
    image: mongo
    container_name: dev_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
